content:
    resource: "@ContentBundle/Resources/config/routing.yml"
    prefix:   /

AppBundle:
    resource: "@AppBundle/Resources/config/routing.yml"

admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

