security:
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user:
            entity:
                class: AppBundle:User
                property: name
        hwi:
            id: hwi_oauth.user.provider

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        default:
            pattern:    ^/
            provider: user
            anonymous: ~

            form_login:
                login_path: login
                check_path: login_check
            oauth:

                resource_owners:
                    vkontakte: vk_check

                login_path: /login-social

                oauth_user_provider:
                    service: hwi_oauth.user.provider

            logout:
                path: logout

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_USER }
