content_post_create:
    path:     /post/create
    defaults: { _controller: ContentBundle:Post:create }

content_post_list:
    path:     /post/list
    defaults: { _controller: ContentBundle:Post:list }

posts:
    type:     rest
    resource: ContentBundle\Controller\API\PostController
    prefix: /api/v1
