services:
    app.admin.post:
        class: ContentBundle\Admin\PostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: "Content", label: "Posts" }
        arguments:
            - ~
            - ContentBundle\Entity\Post
            - ~
        calls:
            - [ setTranslationDomain, [AppBundle]]

    content.form.type.post:
        class: ContentBundle\Form\Type\PostType
        tags:
            - { name: form.type, alias: 'content_post' }

    content.post.entity_listener:
        class: ContentBundle\EntityListener\PostListener
        arguments: [@logger]
        tags:
            - { name: doctrine.orm.entity_listener }
