users:
    type:     rest
    resource: AppBundle\Controller\UsersController

index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

angular:
    path:      /angular
    defaults:  { _controller: AppBundle:Default:angular }

login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

login_check:
    path: /login_check

logout:
    path: /logout
