AppBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: AppBundle\Entity\UserRepository
    entityListeners:
        AppBundle\EntityListener\UserListener: ~
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
       name:
         type: string
    lifecycleCallbacks: {  }
